CREATE TABLE FLASH_CARDS(
    FC_ID NUMBER(38,0),
    FC_QUESTION VARCHAR2(4000) NOT NULL,
    FC_ANSWER VARCHAR2(4000) NOT NULL,
    CONSTRAINT PK_FC_ID PRIMARY KEY (FC_ID),
    CONSTRAINT U_FC_QUESTION UNIQUE(FC_QUESTION));

CREATE SEQUENCE FC_ID_SEQUENCE
MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE OR REPLACE TRIGGER NEW_FLASH_CARD_TRIG
  BEFORE INSERT ON FLASH_CARDS
  FOR EACH ROW
  BEGIN
    SELECT FC_ID_SEQUENCE.NEXTVAL INTO :new.FC_ID FROM DUAL;
  END;
  /
UPDATE FLASH_CARDS SET FC_ID=FC_ID_SEQUENCE.NEXTVAL;

INSERT INTO FLASH_CARDS VALUES(10,'HELLOS?','HI!!!');