/* Initialize tables for the banking app */

CREATE TABLE Users
(
    U_ID NUMBER NOT NULL,
    Username VARCHAR2(10) NOT NULL,
    Password VARCHAR2(10) NOT NULL,
    Type VARCHAR2(10) NOT NULL,
    
    CONSTRAINT USER_PK PRIMARY KEY (U_ID)
);

CREATE TABLE Customers
(
    C_ID NUMBER NOT NULL,
    Username VARCHAR2(10) NOT NULL,
    Balance NUMBER NOT NULL,
    Status NUMBER NOT NULL,
    
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (C_ID),
    CONSTRAINT CUSTOMER_FK FOREIGN KEY (C_ID) REFERENCES Users (U_ID)
);

CREATE TABLE Employees
(
    E_ID NUMBER NOT NULL,
    Username VARCHAR2(10) NOT NULL,
    C_Username VARCHAR2(10) NULL,
    
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (E_ID),
    CONSTRAINT EMPLOYEE_FK FOREIGN KEY (E_ID) REFERENCES Users (U_ID)
);

CREATE TABLE ApplicationRequests
(
    A_ID NUMBER NOT NULL,
    C_ID NUMBER NOT NULL,
    C_Username VARCHAR2(10) NOT NULL,
    
    CONSTRAINT APPREQUEST_PK PRIMARY KEY (A_ID),
    CONSTRAINT APPREQUEST_CUSTOMER_FK FOREIGN KEY (C_ID) REFERENCES Customers (C_ID)
);

COMMIT;