/* 2.0 */

/* 2.1 */
CREATE TABLE Employees
(
    EmployeeID NUMBER NOT NULL,
    UserName VARCHAR(20) NOT NULL,
    Password VARCHAR(20) NOT NULL,
    Name VARCHAR(25) NOT NULL,
    Department CHAR(2) NOT NULL,
    Manager NUMBER NOT NULL,
    CONSTRAINT EMPLOYEES_EID_PK PRIMARY KEY (EmployeeId)
);

CREATE TABLE Orders
(
    OrderID NUMBER NOT NULL,
    EmployeeID NUMBER NOT NULL,
    OrderDate DATE NOT NULL,
    Status CHAR NOT NULL,
    CONSTRAINT ORDERS_OID_PK PRIMARY KEY (OrderId),
    CONSTRAINT ORDERS_EID_FK FOREIGN KEY (EmployeeID) REFERENCES Employees (EmployeeID)
);

CREATE TABLE Supplier
(
    SuppID NUMBER NOT NULL,
    Name VARCHAR(80) NULL,
    CONSTRAINT SuppID PRIMARY KEY (SuppId)
);

CREATE TABLE Category
(
    CatID NUMBER NOT NULL,
    Name VARCHAR(80) NULL,
    Descript VARCHAR(255) NULL,
    CONSTRAINT CatID PRIMARY KEY (CatID)
);

CREATE TABLE Product
(
    ProductID NUMBER NOT NULL,
    CatID NUMBER NOT NULL,
    Name VARCHAR(80) NULL,
    Descript VARCHAR(255) NULL,
    UnitCost NUMBER NULL,
    SuppID NUMBER NOT NULL,
    CONSTRAINT ProductID PRIMARY KEY (ProductId),
    CONSTRAINT PRODUCT_CID_FK FOREIGN KEY (CatID) REFERENCES Category (CatID),
    CONSTRAINT PRODUCT_SID_FK FOREIGN KEY (SuppID) REFERENCES Supplier (SuppID)
);

CREATE TABLE OrderItem
(
    OrderID NUMBER NOT NULL,
    ProductID NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    CONSTRAINT ORDERITEM_OID_PK PRIMARY KEY (OrderId),
    CONSTRAINT ORDERITEM_OID_FK FOREIGN KEY (OrderID) REFERENCES Orders (OrderId),
    CONSTRAINT ORDERITEM_PID_FK FOREIGN KEY (ProductId) REFERENCES Product (ProductId)
);

COMMIT;