--Generate Triggers

--Sequence

CREATE SEQUENCE BA_SEQ MINVALUE 1 MAXVALUE 9999999999999999999
INCREMENT BY 1 START WITH 1;

--Logging Trigger, inputs ID and TIMESTAMP
CREATE OR REPLACE TRIGGER T1
    BEFORE INSERT ON LOGGER
    FOR EACH ROW
    BEGIN
        SELECT BA_SEQ.NEXTVAL INTO    :NEW.LOGID FROM DUAL;
        :NEW.TIMEST := SYSDATE;
    END;
/

--CREATE TABLE LOGGER (LOGID NUMBER(10), TIMEST TIMESTAMP, ACTION VARCHAR(20), USR VARCHAR(30), ACCT VARCHAR(10), AMOUNT VARCHAR(10));

SELECT * FROM LOGGER;
