SELECT * FROM ACCOUNT_STATUS;
SELECT * FROM USER_PRIVILEGES;

CREATE OR REPLACE PROCEDURE REGISTOR_NEW_USER

CREATE OR REPLACE PROCEDURE REG_NEW_USER(
    N_USER_ID IN NUMBER,
    N_USERNAME IN VARCHAR,
    N_PRIVILEGE_ID IN VARCHAR
)AS
BEGIN
    INSERT INTO USERS VALUES (N_USER_ID, N_USERNAME, N_PRIVILEGE_ID);
END;
/