
DROP TABLE CUSTOMER_EMPLOYEE;
DROP TABLE BANK_ACCOUNT;
DROP TABLE USER_TABLE;
DROP TABLE PRIVILEGES_TABLE;
DROP TABLE ACCOUNT_TYPE;
DROP TABLE TRANSACTION_LOG;


CREATE TABLE USER_TABLE
( U_ID NUMBER NOT NULL,
  FIRST_NAME VARCHAR2(20),
  lAST_NAME VARCHAR2(20),
  AGE NUMBER,
  USERNAME VARCHAR2(20) NOT NULL UNIQUE,
  U_PASSWORD VARCHAR2(20) NOT NULL,
  U_PRIVILEGES NUMBER NOT NULL,
  CONSTRAINT PK_U_ID PRIMARY KEY (U_ID)
);

CREATE TABLE PRIVILEGES_TABLE
( PRIV_ID NUMBER NOT NULL,
  PRIV_TYPE VARCHAR2(20),
  CONSTRAINT PK_PRIV_ID PRIMARY KEY (PRIV_ID)
);

CREATE TABLE BANK_ACCOUNT
( LAST_ACCESSED TIMESTAMP NOT NULL,
  ACC_ID NUMBER NOT NULL,
  BALANCE NUMBER,
  U_ID NUMBER NOT NULL,
  ACC_TYPE NUMBER NOT NULL,
  STATUS VARCHAR2(10) NOT NULL,
  CONSTRAINT PK_ACC_ID PRIMARY KEY (ACC_ID)
);

CREATE TABLE ACCOUNT_TYPE
( TYPE_ID NUMBER NOT NULL,
  ACC_TYPE VARCHAR2(10) NOT NULL,
  INTEREST NUMBER(7,2),
  CONSTRAINT PK_TYPE_ID PRIMARY KEY (TYPE_ID)
);

CREATE TABLE CUSTOMER_EMPLOYEE
( CUSTOMER_ID NUMBER NOT NULL,
  EMPLOYEE_ID NUMBER NOT NULL,
  CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES USER_TABLE (U_ID),
  CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES USER_TABLE (U_ID) ON DELETE CASCADE
);

CREATE TABLE TRANSACTION_LOG
( ID NUMBER NOT NULL,
  TIME_STAMP TIMESTAMP NOT NULL,
  ACTIVITY VARCHAR2(10) NOT NULL,
  U_ID NUMBER NOT NULL,
  ACCOUNT NUMBER NOT NULL,
  AMOUNT NUMBER(20,2) NOT NULL,
  CONSTRAINT PK_TRANSACTION_LOG_ID PRIMARY KEY (ID)
);

ALTER TABLE USER_TABLE ADD CONSTRAINT FK_PRIVILEGES
    FOREIGN KEY (U_PRIVILEGES) REFERENCES PRIVILEGES_TABLE (PRIV_ID) ON DELETE CASCADE;
    
ALTER TABLE BANK_ACCOUNT ADD CONSTRAINT FK_UID
    FOREIGN KEY (U_ID) REFERENCES USER_TABLE (U_ID) ON DELETE CASCADE;
    
ALTER TABLE BANK_ACCOUNT ADD CONSTRAINT FK_ACCOUNT_TYPE_ID
    FOREIGN KEY (ACC_TYPE) REFERENCES ACCOUNT_TYPE (TYPE_ID) ON DELETE CASCADE;
    
INSERT INTO PRIVILEGES_TABLE (PRIV_ID, PRIV_TYPE) VALUES (0, 'ADMIN');
INSERT INTO PRIVILEGES_TABLE (PRIV_ID, PRIV_TYPE) VALUES (1, 'CUSTOMER');
INSERT INTO PRIVILEGES_TABLE (PRIV_ID, PRIV_TYPE) VALUES (2, 'EMPLOYEE');

INSERT INTO ACCOUNT_TYPE (TYPE_ID, ACC_TYPE, INTEREST) VALUES (0, 'CHECKING', 0.01);
INSERT INTO ACCOUNT_TYPE (TYPE_ID, ACC_TYPE, INTEREST) VALUES (1, 'SAVINGS', 0.05);

commit;

select * from user_table;
select * from bank_account;
select * from transaction_log;