DROP SEQUENCE USER_SEQ;
DROP SEQUENCE BANKACCOUNT_SEQ;
DROP SEQUENCE TRANSACTION_SEQ;

CREATE SEQUENCE USER_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999999999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE BANKACCOUNT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999999999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE TRANSACTION_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999999999999999 INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER NEW_USER_TRIG
    BEFORE INSERT ON USER_TABLE
    FOR EACH ROW
    BEGIN
        SELECT USER_SEQ.NEXTVAL INTO :new.U_ID FROM DUAL;
    END;
    /
 
 
 CREATE OR REPLACE TRIGGER NEW_ACCOUNT_TRIG
    BEFORE INSERT ON BANK_ACCOUNT
    FOR EACH ROW
    BEGIN
        SELECT BANKACCOUNT_SEQ.NEXTVAL INTO :new.ACC_ID FROM DUAL;
    END;
    /
 
  CREATE OR REPLACE TRIGGER NEW_TRANSACTION_ID_TRIG
    BEFORE INSERT ON TRANSACTION_LOG
    FOR EACH ROW
    BEGIN
        SELECT TRANSACTION_SEQ.NEXTVAL INTO :new.ID FROM DUAL;
    END;
    /
 
 
 CREATE OR REPLACE TRIGGER NEW_TRANSACTION_TRIG
    BEFORE INSERT ON TRANSACTION_LOG
    FOR EACH ROW
    BEGIN
        SELECT SYSTIMESTAMP INTO :new.TIME_STAMP FROM DUAL;
    END;
    /

 CREATE OR REPLACE TRIGGER UPDATE_ACCOUNT_TIMESTAMP_TRIG
    BEFORE UPDATE ON BANK_ACCOUNT
    FOR EACH ROW
    BEGIN
        SELECT SYSTIMESTAMP INTO :new.LAST_ACCESSED FROM DUAL;
    END;
    /

 CREATE OR REPLACE TRIGGER NEW_ACCOUNT_TIMESTAMP_TRIG
    BEFORE INSERT ON BANK_ACCOUNT
    FOR EACH ROW
    BEGIN
        SELECT SYSTIMESTAMP INTO :new.LAST_ACCESSED FROM DUAL;
    END;
    /

commit;