DROP TABLE PRIVILEGES_TABLE CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT_TYPES CASCADE CONSTRAINTS;
DROP TABLE BANKACCOUNTS CASCADE CONSTRAINTS;
DROP TABLE USERINFO CASCADE CONSTRAINTS;
DROP TABLE LOGS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER_EMPLOYEE CASCADE CONSTRAINTS;
DROP SEQUENCE USER_SEQUENCE;
DROP SEQUENCE ACCOUNT_SEQUENCE;
DROP SEQUENCE LOG_SEQUENCE;

CREATE TABLE PRIVILEGES_TABLE(
    PRIVILEGEID NUMBER,
    PRIVILEGE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_PRIVILIGEID PRIMARY KEY(PRIVILEGEID));
    
CREATE TABLE ACCOUNT_TYPES(
    TYPEID NUMBER,
    NAME VARCHAR2(20) NOT NULL,
    INTEREST NUMBER,
    CONSTRAINT PK_TYPEID PRIMARY KEY (TYPEID));
    
CREATE TABLE USERINFO(
    USERID NUMBER,
    FIRST_NAME VARCHAR2(20) NOT NULL,
    LAST_NAME VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR(25) NOT NULL UNIQUE,
    PASSWORD VARCHAR(25) NOT NULL,
    PRIVILEGE NUMBER NOT NULL,
    STATUS NUMBER NOT NULL,
    CONSTRAINT PK_USERID PRIMARY KEY (USERID),
    CONSTRAINT FK_PRIVILEGE FOREIGN KEY (PRIVILEGE) REFERENCES PRIVILEGES_TABLE (PRIVILEGEID));
    
CREATE TABLE BANKACCOUNTS(
    ACCOUNTID NUMBER,
    BALANCE NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    ACCOUNT_TYPEID NUMBER NOT NULL,
    STATUS NUMBER NOT NULL,
    CONSTRAINT PK_ACCOUNTID PRIMARY KEY(ACCOUNTID),
    CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERINFO (USERID),
    CONSTRAINT FK_ACCOUNT_TYPEID FOREIGN KEY(ACCOUNT_TYPEID)REFERENCES ACCOUNT_TYPES (TYPEID));
    
CREATE TABLE LOGS(
    LOGID NUMBER,
    TIMESTAMPS TIMESTAMP NOT NULL,
    ACTIVITY VARCHAR2(200) NOT NULL,
    USERID NUMBER NULL,
    ACCOUNTID NUMBER,
    AMOUNT NUMBER,
    CONSTRAINT PK_LOGID PRIMARY KEY (LOGID),
    CONSTRAINT FK_USERID FOREIGN KEY (USERID) REFERENCES USERINFO (USERID));
    
CREATE TABLE CUSTOMER_EMPLOYEE(
    CUSTOMERID NUMBER,
    EMPLOYEEID NUMBER,
    CONSTRAINT FK_CUSTOMERID FOREIGN KEY (CUSTOMERID) REFERENCES USERINFO (USERID),
    CONSTRAINT FK_EMPLOYEEID FOREIGN KEY (EMPLOYEEID) REFERENCES USERINFO (USERID));
    
INSERT INTO PRIVILEGES_TABLE VALUES (0,'admin');
INSERT INTO PRIVILEGES_TABLE VALUES (1,'employee');
INSERT INTO PRIVILEGES_TABLE VALUES (2,'customer');

CREATE SEQUENCE USER_SEQUENCE
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE ACCOUNT_SEQUENCE
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
CREATE SEQUENCE LOG_SEQUENCE
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

INSERT INTO ACCOUNT_TYPES VALUES(1,'checkings',0);
INSERT INTO ACCOUNT_TYPES VALUES(2,'savings',5.6);

INSERT INTO USERINFO VALUES(USER_SEQUENCE.NEXTVAL,'root','admin','root','admin', 0,1);
INSERT INTO USERINFO VALUES(USER_SEQUENCE.NEXTVAL,'carlos','gastelum','carlos','123',2,1);
INSERT INTO USERINFO VALUES(USER_SEQUENCE.NEXTVAL,'bill','gates','bill','microsoft',1,1);
INSERT INTO BANKACCOUNTS VALUES(ACCOUNT_SEQUENCE.NEXTVAL,600.00,2,1);
INSERT INTO BANKACCOUNTS VALUES(ACCOUNT_SEQUENCE.NEXTVAL,6000.00,2,2);

COMMIT;

SELECT USERNAME FROM USERINFO;

commit;

